controller_manager:
  ros__parameters:
    update_rate: 50

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
      type: velocity_controllers/JointGroupVelocityController

    position_controller:
      type: position_controllers/JointGroupPositionController

    smart_template_controller:
      type: smart_template/SmartTemplateController 

smart_template_controller:
  ros__parameters:
    joints:
      - horizontal_joint  #Channel A
      - insertion_joint   #Channel B
      - vertical_joint    #Channel C
    robot_base_link: base_link
    end_effector_link: needle_link
    interface_name: velocity

velocity_controller:
  ros__parameters:
    joints:
      - horizontal_joint  #Channel A
      - insertion_joint   #Channel B
      - vertical_joint    #Channel C
    interface_name: velocity

position_controller:
  ros__parameters:
    joints:
      - horizontal_joint  #Channel A
      - insertion_joint   #Channel B
      - vertical_joint    #Channel C
    interface_name: position